name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 0 * * *"                                               

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v4
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify date.txt
        run: |
          d=`date '+%Y-%m-%d %H:%M:%S'`
          echo $d > date.txt
          
      - name: Commit changes
        run: |
          git config --local user.name "zayydenzi"
          git config --local user.email "zayydenzi@gmail.com"
          git add -A
          
          d=`date '+%Y-%m-%d %H:%M:%S'`
                    
          git commit -m "Auto commit at $d"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
